### ISSUE TITLE
Discuss relationship to Fisher's theory of Junctions

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#121]
We need a paragraph somewhere summarising Fisher's junctions and how it relates to what we're talking about.

 This [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5947311/) looks like a good starting point. I'm sure Nick Barton and Stuart Baird have done some work on this as well.

Anyone volunteer to dive into this literature?

**Comment by hyanwong** [comment]
I want to read up on this anyway. Happy to be assigned.

**Comment by jeromekelleher** [comment]
Done! I believe there's a Baird, Etheridge & Barton paper somewhere along the line that'll be a good resource.

**Comment by hyanwong** [comment]
> I believe there's a Baird, Etheridge & Barton paper somewhere along the line that'll be a good resource.

Helpful - thanks.

**Comment by hyanwong** [comment]
There's also a relatively recent brief review at https://onlinelibrary.wiley.com/doi/10.1111/jbg.12351

**Comment by petrelharp** [comment]
FYI, when I have looked into this before, the "theory of junctions" is sort of a misnomer: Fisher's paper was about, in modern terms, IBD segments, and more modern continuatoins of this are Kevin Donnelly http://www.ncbi.nlm.nih.gov/pubmed/6857549 or Chapman & Thompson http://www.ncbi.nlm.nih.gov/pubmed/6857549 .  Today though it is, I think, often used to just refer to Fisher's observation that recombination breakpoints are inherited as Mendelian alleles (identifiable as 'junctions' between different haplotypes), which is in some sense complementary to the usual IBD view (as it focuses on the endpoints not the segments).

So, it's a misnomer because it suggests it's a whole 'theory' about something new  - junctions - but really it's just the start of talking about IBD segments / shared haplotypes.  (Also, the paper is, IIRC, in the context of IBD within a known pedigree.)

**Comment by jeromekelleher** [comment]
I think we can close this, it's not needed anywhere in the narrative now.
