### ISSUE TITLE
Name for a fully simplified (coalescent-node only) ARG?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#144]
I'm now thinking of a tree sequence as a container format for edge-annotated gARGs. We can use it to represent an ARG with recombinant nodes and with immediate-inheritance, or one with recombinant nodes and sample resolved inheritance, or ones with only coalescent nodes (i.e. fully simplified).

Instead of using the word "tree sequence", should we therefore have a separate terminology for a fully simplified ARG, of the form produced by msprime? Perhaps a cARG (coalescent-node-only ARG)?

**Comment by JereKoskela** [comment]
I was thinking of ARF (ancestral recombination forest) first to emphasize the fact that it's storing trees, but that didn't sound quite right because the roots still give rise to trees which share branches. Maybe ancestral recombination canopy? Alternatively, a bigger change, e.g. local coalescence graph, might distinguish the fully simplified structure from more traditional ARGs more clearly.

**Comment by jeromekelleher** [comment]
Interesting ideas. :thinking:

**Comment by hyanwong** [comment]
I think we are storing trees in all of them, but we want to emphasise that we are only storing branch points (=coalescent points) in the local trees.  For this reason "local coalescence graph" sounds good to me, although it doesn't immediately say to me that it's a sort of ARG. I guess we could also have "ancestral coalescence graph" too, although "local" is nice.

**Comment by jeromekelleher** [comment]
Ancestral coalescence graph has a good ring to it.
