### ISSUE TITLE
Fig 1 A, B, C

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#206]
The tables in Fig 1 are referred to in the text as (A) and (B), but there are no labels in the actual figure. Do we want to add labels (and maybe use A (LH table), B (graph) C (RH table), or do we want to swap the A, B notation and say "LH table" and "RH table" in the main text?

![Screenshot 2022-04-07 at 10 45 51](https://user-images.githubusercontent.com/4699014/162171417-77adaaaa-5d33-4f83-874a-6c5ff15d953d.png)

**Comment by jeromekelleher** [comment]
The journal is going to want to label the subfigs as A, B  etc, and I don't think there's any point in swimming against the tide there:

> You must submit each figure as an individual image file. Submit all panels of a multipanel figure on a single page as one file. For example, if the figure has 3 panels, the figure should be submitted as one file. Each panel should be labeled as a letter (A, B, C, D, etc.) in the upper-left corner of each panel.

It would be better to accept this and adopt a different node labelling convention now rather than have to fudge it later. This was part of my preference for integers, btw.

**Comment by jeromekelleher** [comment]
Could use lowercase math-mode letters for nodes? That's natural enough.

**Comment by hyanwong** [comment]
I actually meant: do we think of each of the three panels in Fig 1 as subfigures, or do we want to treat it all as a single big figure?

We could use lowercase for node labels if we like. I've been distinguishing them by using sans-serif for the node labels, but perhaps that's not a big enough distinction.

**Comment by jeromekelleher** [comment]
I think it's useful to refer to A B and C in Fig 1. Saying "the bit on the left" is awkward.

Sans-serif won't survive journal typesetting I think. Probably a good idea to have a look at how the [msprime paper](https://academic.oup.com/genetics/article/220/3/iyab229/6460344) figures turned out and adjust accordingly.

**Comment by jeromekelleher** [comment]
SGTM

**Comment by jeromekelleher** [comment]
LGTM
