### ISSUE TITLE
Change direction of ARG edge arrows?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#24]
One tiny nitpick I have with the current ARG viz is that I think the arrows are going in the wrong direction - from parent to child rather than child to parent:

![](https://user-images.githubusercontent.com/4699014/148787129-789b14d7-7acc-4c3d-a232-9210d025a6a2.png)

I understand that time does actually move forwards in the real world, but I think that the ARG is fundamentally a backwards in time structure. This is because it's defined wrt to a given set of samples, and it tracks nodes (~ the subset of the pedigree) that are relevant to the genetic ancestry of those samples. Therefore, an edge in the ARG represents the flow of ancestral material *up* through the graph, not the action of inheritance down.

**Comment by hyanwong** [comment]
I see what you mean, but (a) I worry that focussing on backwards-in-time will make people think that it has to be *generated* backwards in time (which is not necessary, as we see in e.g. SLiM) - thus it might make people fall back into the trap of thinking we are describing a process, rather than a structure, and (b) since in the real world, it actually *is* generated forwards in time, I think it's clearer to show it like this and then afterwards point out that the structure is simplified in some way to remove irrelevant nodes. In fact, even an unsimplified tree sequence e.g. from SLiM could be thought of as a recombination graph, right? (but I concede, perhaps not an *ancestral* recombination graph)

**Comment by jeromekelleher** [comment]
I've been wrestling with this for a few hours, but I think the only sensible definition of an ARG is wrt to the ancestral material of a set of sample genomes. The time direction in which it's generated is irrelevant, it's the fact that the only way in which we can define the nodes (subset of the genomes from the pedigree) that we include is wrt to the coalescences and recombinations that occur to that ancestral material. 

Otherwise it's just a version of the pedigree.

**Comment by jeromekelleher** [comment]
For example, when you draw the arrows pointing downwards, you're implying that this is *all* of the children of a given node. But it's not, it's just the children that have ended up being ancestral to the sample. So, the information fundamentally flows upwards.

**Comment by hyanwong** [comment]
Actually, I do agree with your general point, primarily because of the word "Ancestral" in the ARG. And indeed, the time direction when generating is irrelevant. But I'm still more comfortable with pointing the arrows downwards and explaining that we only include certain children. I think most people (including me) are weirded out by arrows going backwards in time

But perhaps let's see what other people think? We could ask on the #random channel on Slack?

Alternatively, we could have no arrows at all, of course!

**Comment by hyanwong** [comment]
NB, there are, of course, causal effects in this diagram, for example, if there is selection, which is perhaps another reason for being cautious with backwards arrows.

**Comment by jeromekelleher** [comment]
I'd be much happier with no arrows - what purpose do they serve anyway?

**Comment by hyanwong** [comment]
Very true! Let's nuke them then.

**Comment by hyanwong** [comment]
(NB: they do serve a purpose in some cases where an edge accidentally passes through a node visually, but is not actually attached to it in the graph. But we can simply try to avoid those in the examples we choose.

**Comment by hyanwong** [comment]
They've been nuked in the diagrams
