### ISSUE TITLE
Calculations not involving ancestry segments

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#246]
A tiny point, but we say "It is difficult to imagine a practical calculation performed on an ARG that does not involve either the sequential generation of trees along the genome or the resolved ancestry segments."

However, one of the calculations we perform in `tsdate` is to constrain nodes to be strictly older than their oldest child. This doesn't require knowledge of the trees or the segments, simply the graph structure.

There are probably other calculations we could imagine to do with graph topology that don't require knowledge of the edge spans. For example, a reasonable metric might be the average number of parents per node.

**Comment by JereKoskela** [comment]
It sounds like you still need binary information for each edge indicating whether it carries at least one ancestral segment (so that you can discard those which don't), but by my reading that is consistent with our claim.

I guess it's true that you could start with a big ARG, prune non-ancestral edges, run tsdate, and end up with an ancestor node which is younger than a non-genetic child, because you've lost the information that it's a child at all. But I think we catch that situation by focusing on practical calculations: graph structures which haven't been ancestry-resolved will just be too big to be useful.

**Comment by jeromekelleher** [comment]
I think the basic point is reasonable, but maybe we should tone down the rhetoric.
