### ISSUE TITLE
Replace "edge annotations" with "edge intervals"

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#254]
There are quite a few places that we use the phrase "edge annotations" to mean "intervals of genetic inheritance associated with an edge". I think it would be better if we used the phrase "edge intervals" instead:

- I think "annotations" will be confusing for some people, as it will be interpreted in the [genome annotation](https://www.google.com/search?q=genome+annotation) sense
- The word is very generic - *what* are we annotating the edges with?

"Edge intervals" is a bit more concrete and precise, and lends itself to usage like "we update the outbound edge intervals to remove non-ancestral segments" etc.

**Comment by hyanwong** [comment]
I think this is so that we can talk about "node annotated" vs "edge annotated" ARGs. I guess we can't talk about "node intervals" though. Is there another phrasing that we can use instead of "edge annotated ARGs" that would do the trick, and allow continuity with the later descriptions of edge intervals? If we talk about an "edge annotated ARG" then go on to talk about edge intervals, I worry that the connection may not be made by a skimming reader.

**Comment by jeromekelleher** [comment]
I don't think we need to focus so much on the distinction (it's relative straightforward to see and we have more interesting things to talk about), but yes, good point.
