### ISSUE TITLE
Fig 4 (simplification) - remove edges above local roots

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#267]
We want the figure in 4A to correspond to something that we get after doing sample resolution. So I think we should remove the edges above local roots (i.e. in the last tree in 4A the root should be `k` and in the penultimate tree it should be `q`)
<img width="1070" alt="Screenshot 2022-09-29 at 15 10 15" src="https://user-images.githubusercontent.com/4699014/193054553-71c345e4-0da3-4922-b499-89e5c7cd0e63.png">

**Comment by jeromekelleher** [comment]
It's not totally obvious that's what should be done I think. Perhaps we would wish to maintain the information that e.g. q is still the ancestor of k on 70-100.

**Comment by jeromekelleher** [comment]
Hmm, where did we get it from?

**Comment by hyanwong** [comment]
It's an example from the WF simulator that you wrote.

**Comment by jeromekelleher** [comment]
Is this a bug in ``sim_wright_fisher`` then? If not, then I don't think we should change the figure.

**Comment by hyanwong** [comment]
I think it's probably a bug, if you intended not to track ancestry above the local root. We could either fix the bug or simply snip it out (I have a function for doing that)

**Comment by jeromekelleher** [comment]
I'm not sure it is, the comment [here](https://github.com/tskit-dev/what-is-an-arg-paper/blob/d4d14fccfcd57212283ab4674a9092d55684e275/argutils/ancestry.py#L217) implies that we do need to keep tracking lineages after coalescence, and that we quite deliberately *don't* snip these out.

Hmm, I guess it's so that we have a "full" ARG, which has complete information about the relationship between genomes, as simulated. "Knowability" is irrelevant here, because we simulated this information and these are the full details. If you stop tracking lineages after the local roots, you do lose information about deeper relationships (which we've definitely gone through before). A "full" ARG does have information about things that happen above the local roots, and we should faithfully depict this.

I think we should keep things as they are, there were good reasons for setting things up this way.

**Comment by jeromekelleher** [comment]
(A) is a gARG that encodes the complete relationships between genomes that are genetic ancestors of the sample, and subsequent panels are the results of sequentially simplifying that. We totally shouldn't start with something that's already partially simplified.

**Comment by hyanwong** [comment]
Good spot on that comment: sorry I missed it. But I think it was you who wanted to make one of the panels in fig 4 an equivalent to Fig 3C?

 > "Knowability" is irrelevant here, because we simulated this information and these are the full details.

Yes, I agree this is irrelevant. We don't have the full details though: by design, we've already "simplified out" the nodes in which nothing happens.

I'm not sure I'd see keeping or discarding the topology above the root as specifically a feature of tskit simplification: you could easily not record it in the first place. Moreover, we're not removing any node here. Also, you could argue that if this was a forward simulation, we have already performed the sample-resolving step, which we have previously claimed could involve removing edges above local roots.

But it's all a minor thing really: I don't think may people will notice. Let's leave it as is unless there are strong views either way, and see how it fits into the graphical flow.

**Comment by JereKoskela** [comment]
I'm late to the party and I haven't ever spent much time thinking about forward simulators, but Yan's suggestion above sounds good to me.
