### ISSUE TITLE
New section to describe example ARGs

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#393]
We only discuss the inferred ARGs figure in one paragraph at the moment, and it's used as a sort of side-effect of the discussion of recombination precision. We want a new section, to describe and discuss.

We can call it "Example inferred ARGs" for now, until we think of a better title.

**Comment by jeromekelleher** [comment]
I think this is a good potential lead-in:

> The substantial scalability gains made by recent inference methods have in part been due to inferring lower levels of precision about recombination. However, the properties of the ARGs are not well understood, and (in particular) Relate and tsinfer have been mischaracterised as inferring sequences of *unrelated* trees [cites]. In this section we visually compare the output of recent ARG inference methods on the Kreitman dataset, a standard benchmark in the classical ARG literature, to illustrate the qualitative properties of these ARGs.


See #38 for some links on the mischaracterisation.

**Comment by jeromekelleher** [comment]
@a-ignatieva can you think of any papers where people have mischaracterised Relate output in particular?

**Comment by a-ignatieva** [comment]
I think this is a bit tricky - a lot of papers (including those listed in #38) say ambiguous things like "infer a series of local trees" or "infer only the local trees", but this isn't wrong necessarily depending on interpretation? I don't think it necessarily implies "trees inferred independently in sections of the genome". I mean Hubisz Siepel 2020 say "The ARG, therefore, can be thought of as being interchangeable with a sequence of local trees and the associated recombination events that transform each tree to the next.", and I suspect when most people say Relate and tsinfer don't infer ARGs, it's because they output the "sequence of local trees" but not the "associated recombination events". Of course this is all sort of the point of the paper, but I just wonder if worth spelling this out explicitly when referring to the other work (rather than just citing as examples of "incorrect").

**Comment by a-ignatieva** [comment]
I can have a go at writing this in a para and we can see if we all agree on the message?

**Comment by jeromekelleher** [comment]
Sure, go ahead. I don't really mind what the message is once it's reasonably easy to follow and gives us a reason to talk about the qualitative differences between the ARGs from the four methods.

I think we do need to point out that people are misrepresenting stuff, or at least that they are confused/being confusing.

**Comment by hyanwong** [comment]
Fixed in #398
